name: Tests

on:
  push:
    branches:
      - main

jobs:
  run_checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytest pytest-cov flake8 black mypy bandit

      # Step 4: Run Flake8
      - name: Run Flake8
        run: flake8 .

      # Step 5: Run Black
      - name: Run Black
        run: black --check .

      # Step 6: Run mypy
      - name: Run mypy
        run: mypy .

      # Step 7: Run Bandit
      - name: Run Bandit
        run: bandit -c .bandit.yml -r .

      # Step 8: Run tests with pytest and generate coverage report
      - name: Run tests with pytest
        run: |
          pytest tests/test_myfile.py --doctest-modules --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html

      # Step 9: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Use GitHub Secrets for the token
          file: ./coverage.xml  # Path to the coverage report
          flags: unittests  # Optional: Add flags to categorize the coverage